In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
train_set= pd.read_csv("Train_dataset.csv")
test_set= pd.read_csv("Test_dataset.csv")

In [5]:
train_set.head()

      SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN age_group
0  73564.0       2.0     2.0    35.7   110.0     2.0   150.0  14.91     Adult
1  73568.0       2.0     2.0    20.3    89.0     2.0    80.0   3.85     Adult
2  73576.0       1.0     2.0    23.2    89.0     2.0    68.0   6.14     Adult
3  73577.0       1.0     2.0    28.9   104.0     NaN    84.0  16.15     Adult
4  73580.0       2.0     1.0    35.9   103.0     2.0    81.0  10.92     Adult

In [7]:
X_train= train_set.drop(columns="age_group")
y_train= train_set["age_group"]
X_train.head()

      SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN
0  73564.0       2.0     2.0    35.7   110.0     2.0   150.0  14.91
1  73568.0       2.0     2.0    20.3    89.0     2.0    80.0   3.85
2  73576.0       1.0     2.0    23.2    89.0     2.0    68.0   6.14
3  73577.0       1.0     2.0    28.9   104.0     NaN    84.0  16.15
4  73580.0       2.0     1.0    35.9   103.0     2.0    81.0  10.92

In [8]:
y_train.head()

0    Adult
1    Adult
2    Adult
3    Adult
4    Adult
Name: age_group, dtype: str