In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train_set= pd.read_csv("Train_dataset.csv")
test_set= pd.read_csv("Test_dataset.csv")

In [3]:
train_set.head()

      SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN age_group
0  73564.0       2.0     2.0    35.7   110.0     2.0   150.0  14.91     Adult
1  73568.0       2.0     2.0    20.3    89.0     2.0    80.0   3.85     Adult
2  73576.0       1.0     2.0    23.2    89.0     2.0    68.0   6.14     Adult
3  73577.0       1.0     2.0    28.9   104.0     NaN    84.0  16.15     Adult
4  73580.0       2.0     1.0    35.9   103.0     2.0    81.0  10.92     Adult

In [5]:
train_set.isnull().mean()*100

SEQN         0.610376
RIAGENDR     0.915565
PAQ605       0.661241
BMXBMI       0.915565
LBXGLU       0.661241
DIQ010       0.915565
LBXGLT       0.559512
LBXIN        0.457782
age_group    0.712106
dtype: float64

In [6]:
mode_age_group = train_set["age_group"].mode()[0]
train_set["age_group"] = train_set["age_group"].fillna(mode_age_group)

In [7]:
train_set.isnull().mean()*100

SEQN         0.610376
RIAGENDR     0.915565
PAQ605       0.661241
BMXBMI       0.915565
LBXGLU       0.661241
DIQ010       0.915565
LBXGLT       0.559512
LBXIN        0.457782
age_group    0.000000
dtype: float64

In [8]:
cols= [var for var in train_set.columns if train_set[var].isnull().mean()*100 > 0]

In [9]:
cols

['SEQN', 'RIAGENDR', 'PAQ605', 'BMXBMI', 'LBXGLU', 'DIQ010', 'LBXGLT', 'LBXIN']

In [12]:
for var in cols:
    mean= train_set[var].mean()
    train_set[var]=train_set[var].fillna(mean)

In [13]:
train_set.isnull().mean()*100

SEQN         0.0
RIAGENDR     0.0
PAQ605       0.0
BMXBMI       0.0
LBXGLU       0.0
DIQ010       0.0
LBXGLT       0.0
LBXIN        0.0
age_group    0.0
dtype: float64

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
age=["Adult","Senior"]
enc= OrdinalEncoder(categories=[age])
train_set["age_group"]= enc.fit_transform(train_set[["age_group"]])

In [19]:
train_set.head(20)

,SEQN,RIAGENDR,PAQ605,BMXBMI,LBXGLU,DIQ010,LBXGLT,LBXIN,age_group
0,73564.0,2.0,2.0,35.7,110.0,2.000000,150.0,14.91,0.0
1,73568.0,2.0,2.0,20.3,89.0,2.000000,80.0,3.85,0.0
2,73576.0,1.0,2.0,23.2,89.0,2.000000,68.0,6.14,0.0
3,73577.0,1.0,2.0,28.9,104.0,2.015914,84.0,16.15,0.0
4,73580.0,2.0,1.0,35.9,103.0,2.000000,81.0,10.92,0.0
5,73581.0,1.0,2.0,23.6,110.0,2.000000,100.0,6.08,0.0
6,73587.0,1.0,2.0,38.7,94.0,2.000000,202.0,21.11,0.0
7,73596.0,2.0,2.0,38.3,107.0,2.000000,164.0,20.93,0.0
8,73607.0,1.0,2.0,38.9,89.0,2.000000,113.0,17.47,1.0
9,73610.0,1.0,1.0,28.9,90.0,2.000000,95.0,3.24,0.0
10,73618.0,2.0,2.0,32.7,98.0,2.000000,80.0,7.16,0.0
11,73619.0,2.0,1.0,27.3,85.0,2.000000,91.0,9.86,0.0
12,73621.0,1.0,2.0,24.6,100.0,2.000000,97.0,4.33,1.0
13,73633.0,2.0,2.0,30.5,102.0,2.000000,124.0,12.06,0.0
14,73639.0,1.0,2.0,30.3,133.0,2.000000,295.0,22.92,1.0
15,73640.0,2.0,1.0,22.1,114.0,2.000000,150.0,10.09,1.0
16,73642.0,2.0,2.0,37.8,96.0,2.000000,120.0,9.61,0.0
17,73656.0,1.0,2.0,28.0,89.0,2.000000,82.0,8.39,0.0
18,73661.0,1.0,2.0,21.0,86.0,2.000000,84.0,4.47,0.0
19,73663.0,1.0,2.0,33.0,108.0,2.000000,77.0,8.02,0.0

In [23]:
X_train= train_set.drop(columns="age_group")
y_train= train_set["age_group"]

In [24]:
X_train.head()

      SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU    DIQ010  LBXGLT  LBXIN
0  73564.0       2.0     2.0    35.7   110.0  2.000000   150.0  14.91
1  73568.0       2.0     2.0    20.3    89.0  2.000000    80.0   3.85
2  73576.0       1.0     2.0    23.2    89.0  2.000000    68.0   6.14
3  73577.0       1.0     2.0    28.9   104.0  2.015914    84.0  16.15
4  73580.0       2.0     1.0    35.9   103.0  2.000000    81.0  10.92

In [25]:
y_train.head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: age_group, dtype: float64